/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ballboy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {

    @Test
    public void dummy() {
//        assertTrue(false);
    }
}
